/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicTIdRouteImport } from './routes/api/public/t.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTIdRoute = ApiPublicTIdRouteImport.update({
  id: '/api/public/t/$id',
  path: '/api/public/t/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/t/$id': typeof ApiPublicTIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/t/$id': typeof ApiPublicTIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/t/$id': typeof ApiPublicTIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/t/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/t/$id'
  id: '__root__' | '/' | '/api/public/t/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicTIdRoute: typeof ApiPublicTIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/t/$id': {
      id: '/api/public/t/$id'
      path: '/api/public/t/$id'
      fullPath: '/api/public/t/$id'
      preLoaderRoute: typeof ApiPublicTIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicTIdRoute: ApiPublicTIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
