/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram.webhook'
import { Route as ApiPublicTIdRouteImport } from './routes/api/public/t.$id'
import { Route as ApiPublicCronDistributeRouteImport } from './routes/api/public/cron.distribute'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTIdRoute = ApiPublicTIdRouteImport.update({
  id: '/api/public/t/$id',
  path: '/api/public/t/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronDistributeRoute = ApiPublicCronDistributeRouteImport.update({
  id: '/api/public/cron/distribute',
  path: '/api/public/cron/distribute',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/cron/distribute': typeof ApiPublicCronDistributeRoute
  '/api/public/t/$id': typeof ApiPublicTIdRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/cron/distribute': typeof ApiPublicCronDistributeRoute
  '/api/public/t/$id': typeof ApiPublicTIdRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/cron/distribute': typeof ApiPublicCronDistributeRoute
  '/api/public/t/$id': typeof ApiPublicTIdRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/cron/distribute'
    | '/api/public/t/$id'
    | '/api/public/telegram/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/public/cron/distribute'
    | '/api/public/t/$id'
    | '/api/public/telegram/webhook'
  id:
    | '__root__'
    | '/'
    | '/api/public/cron/distribute'
    | '/api/public/t/$id'
    | '/api/public/telegram/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicCronDistributeRoute: typeof ApiPublicCronDistributeRoute
  ApiPublicTIdRoute: typeof ApiPublicTIdRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/t/$id': {
      id: '/api/public/t/$id'
      path: '/api/public/t/$id'
      fullPath: '/api/public/t/$id'
      preLoaderRoute: typeof ApiPublicTIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/distribute': {
      id: '/api/public/cron/distribute'
      path: '/api/public/cron/distribute'
      fullPath: '/api/public/cron/distribute'
      preLoaderRoute: typeof ApiPublicCronDistributeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicCronDistributeRoute: ApiPublicCronDistributeRoute,
  ApiPublicTIdRoute: ApiPublicTIdRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
