/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RCodeRouteImport } from './routes/r.$code'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram.webhook'
import { Route as ApiPublicTIdRouteImport } from './routes/api/public/t.$id'
import { Route as ApiPublicRCodeRouteImport } from './routes/api/public/r.$code'
import { Route as ApiPublicCronRefreshStatsRouteImport } from './routes/api/public/cron.refresh-stats'
import { Route as ApiPublicCronDistributeRouteImport } from './routes/api/public/cron.distribute'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RCodeRoute = RCodeRouteImport.update({
  id: '/r/$code',
  path: '/r/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTIdRoute = ApiPublicTIdRouteImport.update({
  id: '/api/public/t/$id',
  path: '/api/public/t/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRCodeRoute = ApiPublicRCodeRouteImport.update({
  id: '/api/public/r/$code',
  path: '/api/public/r/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronRefreshStatsRoute =
  ApiPublicCronRefreshStatsRouteImport.update({
    id: '/api/public/cron/refresh-stats',
    path: '/api/public/cron/refresh-stats',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronDistributeRoute = ApiPublicCronDistributeRouteImport.update({
  id: '/api/public/cron/distribute',
  path: '/api/public/cron/distribute',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/r/$code': typeof RCodeRoute
  '/api/public/cron/distribute': typeof ApiPublicCronDistributeRoute
  '/api/public/cron/refresh-stats': typeof ApiPublicCronRefreshStatsRoute
  '/api/public/r/$code': typeof ApiPublicRCodeRoute
  '/api/public/t/$id': typeof ApiPublicTIdRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/r/$code': typeof RCodeRoute
  '/api/public/cron/distribute': typeof ApiPublicCronDistributeRoute
  '/api/public/cron/refresh-stats': typeof ApiPublicCronRefreshStatsRoute
  '/api/public/r/$code': typeof ApiPublicRCodeRoute
  '/api/public/t/$id': typeof ApiPublicTIdRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/r/$code': typeof RCodeRoute
  '/api/public/cron/distribute': typeof ApiPublicCronDistributeRoute
  '/api/public/cron/refresh-stats': typeof ApiPublicCronRefreshStatsRoute
  '/api/public/r/$code': typeof ApiPublicRCodeRoute
  '/api/public/t/$id': typeof ApiPublicTIdRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/r/$code'
    | '/api/public/cron/distribute'
    | '/api/public/cron/refresh-stats'
    | '/api/public/r/$code'
    | '/api/public/t/$id'
    | '/api/public/telegram/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/r/$code'
    | '/api/public/cron/distribute'
    | '/api/public/cron/refresh-stats'
    | '/api/public/r/$code'
    | '/api/public/t/$id'
    | '/api/public/telegram/webhook'
  id:
    | '__root__'
    | '/'
    | '/r/$code'
    | '/api/public/cron/distribute'
    | '/api/public/cron/refresh-stats'
    | '/api/public/r/$code'
    | '/api/public/t/$id'
    | '/api/public/telegram/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RCodeRoute: typeof RCodeRoute
  ApiPublicCronDistributeRoute: typeof ApiPublicCronDistributeRoute
  ApiPublicCronRefreshStatsRoute: typeof ApiPublicCronRefreshStatsRoute
  ApiPublicRCodeRoute: typeof ApiPublicRCodeRoute
  ApiPublicTIdRoute: typeof ApiPublicTIdRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$code': {
      id: '/r/$code'
      path: '/r/$code'
      fullPath: '/r/$code'
      preLoaderRoute: typeof RCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/t/$id': {
      id: '/api/public/t/$id'
      path: '/api/public/t/$id'
      fullPath: '/api/public/t/$id'
      preLoaderRoute: typeof ApiPublicTIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/r/$code': {
      id: '/api/public/r/$code'
      path: '/api/public/r/$code'
      fullPath: '/api/public/r/$code'
      preLoaderRoute: typeof ApiPublicRCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/refresh-stats': {
      id: '/api/public/cron/refresh-stats'
      path: '/api/public/cron/refresh-stats'
      fullPath: '/api/public/cron/refresh-stats'
      preLoaderRoute: typeof ApiPublicCronRefreshStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/distribute': {
      id: '/api/public/cron/distribute'
      path: '/api/public/cron/distribute'
      fullPath: '/api/public/cron/distribute'
      preLoaderRoute: typeof ApiPublicCronDistributeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RCodeRoute: RCodeRoute,
  ApiPublicCronDistributeRoute: ApiPublicCronDistributeRoute,
  ApiPublicCronRefreshStatsRoute: ApiPublicCronRefreshStatsRoute,
  ApiPublicRCodeRoute: ApiPublicRCodeRoute,
  ApiPublicTIdRoute: ApiPublicTIdRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
